### ISSUE TITLE
R markdown document does not process numbers with commas correctly

### ISSUE THREAD

**Issue by tatumdmortimer** [ONeillMB1/alignmentQC#1]
R markdown was treating numbers with commas as factors instead of numeric, which was messing up the ordering of the plots. My fix was the following, but there might be a more elegant way?

`#read in the files
dat <- read.csv(filepath, header=T, sep='\t', na.strings="NA", 
                stringsAsFactors=FALSE)
# Some columns have commas in the numbers, so we need to change that.

dat$misMat <- as.numeric(gsub(",","",dat$misMat))
dat$numIns <- as.numeric(gsub(",","",dat$numIns))
dat$numDel <- as.numeric(gsub(",","",dat$numDel))
dat$meanIns <- as.numeric(gsub(",","",dat$meanIns))
dat$medIns <- as.numeric(gsub(",","",dat$medIns))
dat$stdIns <- as.numeric(gsub(",","",dat$stdIns))`

**Comment by ONeillMB1** [comment]
Resolved! 09c262707f9298c7667f337c0f92d6ad661949b9
